### ISSUE TITLE
Duplicated timeseries in CollectorRegistry

### ISSUE THREAD

**Issue by giuseppecunsolo-sky** [giuseppecunsolo-sky/gcp-quota-exporter#4]
Just adding this issue to document the error and the following implementation decision.

As we are trying to create metrics dynamically the `CollectorRegistry` is not happy:

```
2020-07-27 09:51:41,901 INFO:metrics collected successfully (1595843501.9013608)
2020-07-27 09:51:41,901 INFO:found 11 metric limits and 17 metric values
2020-07-27 09:51:41,901 INFO:metrics updated
k: compute__forwarding_rules__global
v: {'full_name': 'compute.googleapis.com/forwarding_rules', 'short_name': 'compute__forwarding_rules', 'location': 'global', 'location_short': 'global', 'service': 'compute.googleapis.com', 'kind': 1, 'limit': [int64_value: 8
]}
k: compute__global_in_use_addresses__global
v: {'full_name': 'compute.googleapis.com/global_in_use_addresses', 'short_name': 'compute__global_in_use_addresses', 'location': 'global', 'location_short': 'global', 'service': 'compute.googleapis.com', 'kind': 1, 'limit': [int64_value: 4
]}

2020-07-27 09:52:41,947 INFO:executing the while loop
2020-07-27 09:52:41,947 INFO:gathering metrics
2020-07-27 09:52:43,443 INFO:metrics collected successfully (1595843563.4430106)
2020-07-27 09:52:43,443 INFO:found 11 metric limits and 17 metric values
2020-07-27 09:52:43,443 INFO:metrics updated
Traceback (most recent call last):
  File "test.py", line 197, in <module>
    main()
  File "test.py", line 182, in main
    quota.generate_usage_metrics()  # DEBUG
  File "test.py", line 143, in generate_usage_metrics
    _g = Gauge(f'gcp_quota_{k}', 'Something Something')
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/metrics.py", line 331, in __init__
    super(Gauge, self).__init__(
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/metrics.py", line 121, in __init__
    registry.register(self)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py", line 29, in register
    raise ValueError(
ValueError: Duplicated timeseries in CollectorRegistry: {'gcp_quota_compute__forwarding_rules__global'}
```

The way forward seems to be to create a [custom collector](https://github.com/prometheus/client_python#custom-collectors) as suggested [here: Create Prometheus metrics from a dynamic source in Python](https://albersdevelopment.net/2019/09/24/create-prometheus-metrics-from-a-dynamic-source-in-python/).

**Comment by giuseppecunsolo-sky** [comment]
just adding here a code snippet for reference, this will update a number (10) of dynamically generated metrics + one static metric:

```
from prometheus_client import start_http_server, Gauge
from prometheus_client.core import GaugeMetricFamily, REGISTRY

import time
import random

from prometheus_client.core import GaugeMetricFamily, CounterMetricFamily, REGISTRY


class CustomCollector(object):
    def collect(self):
        for i in range(10):
            metric_name = f"gcp_quota_test_{i+1}_total"
            print(f"new metric name: {metric_name}")
            gf = GaugeMetricFamily(metric_name, f'Help text for {metric_name}', value=random.random())
            print("added metric name")
            yield gf



if __name__ == "__main__":
    start_http_server(8000)

    REGISTRY.register(CustomCollector())
    print("register")

    g = Gauge(f'gcp_quota_test_total', 'test test')

    while True:
        g.set_to_current_time()
        g.set(random.random())
        print(g)
        time.sleep(15)
```

**Comment by giuseppecunsolo-sky** [comment]
Managed to get the CustomCollector working in 0d9d5c4

For the time being we are just using `random.random()` as metric value just for debugging/developing. Still working on getting the metric value into something we can use, I will open a new issue to track that.
