### ISSUE TITLE
How can we use int64_value with prometheus_client ?

### ISSUE THREAD

**Issue by giuseppecunsolo-sky** [giuseppecunsolo-sky/gcp-quota-exporter#5]
After implementing the `CustomCollector` we now have a dynamically generated list of metrics that is built at runtime.

This is just an excerpt of the metrics:
```
(...)
2020-07-31 14:17:18,649 DEBUG:compute__ssd_total_storage__europe_west1_d: int64_value: 1325
2020-07-31 14:17:18,650 DEBUG:compute__backend_services__global: int64_value: 4
2020-07-31 14:17:18,650 DEBUG:compute__cpus_all_regions__global: int64_value: 0
2020-07-31 14:17:18,650 DEBUG:compute__forwarding_rules__global: int64_value: 8
2020-07-31 14:17:18,650 DEBUG:compute__global_in_use_addresses__global: int64_value: 4
2020-07-31 14:17:18,650 DEBUG:compute__gpus_all_regions__global: int64_value: 0
2020-07-31 14:17:18,650 DEBUG:compute__health_checks__global: int64_value: 7
2020-07-31 14:17:18,650 DEBUG:compute__instance_templates__global: int64_value: 11
2020-07-31 14:17:18,650 DEBUG:compute__snapshots__global: int64_value: 1
2020-07-31 14:17:18,650 DEBUG:compute__target_pools__global: int64_value: 4
2020-07-31 14:17:18,650 DEBUG:iam__quota__service_account_count__global: int64_value: 44
```

Note that the metric name is built from `.metric.labels['quota_metric']` after some transformation to make it compliant with the Prometheus metric names (e.g., no dashes `-`).

We are including into the metric name the `service` and then, separated by a double underscore (`__`), the short metric name and, again separated by a double underscore, the location (e.g., `global`, `europe_west1_d`, etc.)

Now, the value is an `int64_value` which causes `prometheus_client` to raise a `TypeError` if we try to use it as it is:

```
2020-07-31 14:01:18,643 DEBUG:compute__a2_cpus__europe_west1: int64_value: 0

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/exposition.py", line 52, in prometheus_app
    status, header, output = _bake_output(registry, accept_header, params)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/exposition.py", line 40, in _bake_output
    output = encoder(registry)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/openmetrics/exposition.py", line 56, in generate_latest
    floatToGoString(s.value),
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/utils.py", line 9, in floatToGoString
    d = float(d)
TypeError: ("float() argument must be a string or a number, not 'TypedValue'", Metric(gcp_quota_compute__a2_cpus__europe_west1, Help text for quota test metric compute__a2_cpus__europe_west1, gauge, , [Sample(name='gcp_quota_compute__a2_cpus__europe_west1', labels={}, value=int64_value: 0
, timestamp=None, exemplar=None)]))
```

**Comment by giuseppecunsolo-sky** [comment]
I found [this post: Downsampling and Exporting Stackdriver Monitoring Data](https://medium.com/google-cloud/downsampling-and-exporting-stackdriver-monitoring-data-c3483e88a352) which seems to offer more insight and potentially a way forward.

**Comment by giuseppecunsolo-sky** [comment]
It does indeed work. Leaving it here for reference:

```
(Pdb) pp entry.points[0]
interval {
  start_time {
    seconds: 1596445355
    nanos: 84442000
  }
  end_time {
    seconds: 1596445355
    nanos: 84442000
  }
}
value {
  int64_value: 0
}

(Pdb) pp entry.points[0].value
int64_value: 0

(Pdb) pp entry.points[0].value.int64_value
0
(Pdb) pp type(entry.points[0].value.int64_value)
<class 'int'>
```

**Comment by giuseppecunsolo-sky** [comment]
done in c26b828 

Introduced a new class (`MetricValues`) to deal with the details of unpacking the timestamp, value and returning the latest (most recent) value.
